// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "Scr.h"
#include "ui/ui.h" // sketchy backwards import may break in the future

Scr::Scr(lv_image_dsc_t navbarImage)
{
    this->navbarImage = navbarImage;
}

void Scr::init()
{
    this->scr = lv_obj_create(NULL);
    lv_obj_remove_flag(this->scr, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // background color
    this->rect_bg = lv_obj_create(this->scr);
    lv_obj_remove_style_all(this->rect_bg);
    lv_obj_set_size(this->rect_bg, 240, 320);
    lv_obj_set_align(this->rect_bg, LV_ALIGN_TOP_MID);
    lv_obj_get_style_border_width(this->rect_bg, 0);
    lv_obj_set_style_bg_color(this->rect_bg, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(this->rect_bg, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE)); /// Flags
    lv_obj_set_style_bg_opa(this->rect_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // navbar image
    this->icon_navbar = lv_image_create(this->scr);
    lv_image_set_src(this->icon_navbar, &this->navbarImage);
    lv_obj_set_align(this->icon_navbar, LV_ALIGN_BOTTOM_MID);

    this->alert = new Alert(this);
}

// down = true when just pressed, false when just released
void Scr::runTouchInput(SimplePoint pos, bool down)
{
    if (sr_contains(navbarbtn_home, pos))
    {
        changeScreen(SCREEN_HOME);
    }
    if (sr_contains(navbarbtn_presets, pos))
    {
        changeScreen(SCREEN_PRESETS);
    }
    if (sr_contains(navbarbtn_settings, pos))
    {
        changeScreen(SCREEN_SETTINGS);
    }
}

void Scr::loop()
{
    dialogLoop(this);
    SimplePoint tp = {touchX(), touchY()};
    if (isJustPressed())
    {
        this->runTouchInput(tp, true);
    }
    if (isJustReleased())
    {
        this->runTouchInput(tp, false);
    }
}