// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui_scrHome.h"

ScrHome scrHome;

void ui_scrHome_screen_init(void);

LV_IMG_DECLARE(home_bg);

void ui_scrHome_screen_init(void)
{
    scrHome.ui_scrHome = lv_obj_create(NULL);
    lv_obj_remove_flag(scrHome.ui_scrHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    scrHome.ui_scrHome_icon_home_bg = lv_image_create(scrHome.ui_scrHome);
    lv_image_set_src(scrHome.ui_scrHome_icon_home_bg, &home_bg);
    lv_obj_center(scrHome.ui_scrHome_icon_home_bg);

}

void ui_scrHome_loop() {


}