// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui_scrHome.h"

ScrHome scrHome;

SimpleRect button1 = {0, 0, 0, 0};

LV_IMG_DECLARE(home_bg);

void ui_scrHome_screen_init(void)
{
    scrHome.ui_scrHome = lv_obj_create(NULL);
    lv_obj_remove_flag(scrHome.ui_scrHome, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    scrHome.ui_scrHome_icon_home_bg = lv_image_create(scrHome.ui_scrHome);
    lv_image_set_src(scrHome.ui_scrHome_icon_home_bg, &home_bg);
    lv_obj_center(scrHome.ui_scrHome_icon_home_bg);
}

#define ARROW_BUTTON_WIDTH 54
#define ARROW_BUTTON_HEIGHT 44

// idk the names so doing grid pattern

// first column (left)
CenterRect ctr_row0col0up = {48, 89, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row0col0down = {48, 137, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

CenterRect ctr_row1col0up = {48, 193, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row1col0down = {48, 241, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

// second column (center)
CenterRect ctr_row0col1up = {118, 78, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row0col1down = {118, 126, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

CenterRect ctr_row1col1up = {118, 204, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row1col1down = {118, 252, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

// third column (right)
CenterRect ctr_row0col2up = {189, 89, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row0col2down = {189, 137, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

CenterRect ctr_row1col2up = {189, 193, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};
CenterRect ctr_row1col2down = {189, 241, ARROW_BUTTON_WIDTH, ARROW_BUTTON_HEIGHT};

// bottom nav
SimpleRect navbarbtn_home = {0, 291, 80, 29};
SimpleRect navbarbtn_presets = {80, 291, 80, 29};
SimpleRect navbarbtn_settings = {160, 291, 80, 29};

// down = true when just pressed, false when just released
void runTouchInput(SimplePoint pos, bool down)
{
    if (cr_contains(ctr_row0col0up, pos))
    {
        log_i("pressed ctr_row0col0up");
    }
}

void ui_scrHome_loop()
{

    if (isJustPressed())
    {
        SimplePoint tp = {touchX(), touchY()};
        runTouchInput(tp, true);
    }
}