// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "waveshare/board_driver_util.h"
#include "utils/touch_lib.h"
#include "components/alert.h"
#include "components/navbar.h"
#include "components/statusbar.h"

LV_IMG_DECLARE(oasman_splash);

SCREEN currentScreen = SCREEN_NONE;
static lv_obj_t* mainScreen = nullptr;

// Tab change callback - updates currentScreen and currentScr
static void onTabChanged(uint32_t tabIndex) {
    SCREEN newScreen = (SCREEN)(tabIndex + 1);  // SCREEN_HOME = 1
    if (currentScreen == newScreen) return;

    currentScreen = newScreen;
    currentScr = screens[tabIndex];

    // Sync alert icon state from global dismissed state when changing screens
    if (currentScr != nullptr && currentScr->alert != nullptr) {
        currentScr->alert->syncFromGlobal();
    }

    // Run one screen loop of the new screen to update things like the alert
    screenLoop();
}

void ui_init(void)
{
    // Get reference to temporary screen from board_drivers_init (if any)
    lv_obj_t *tempScr = lv_screen_active();

    lv_display_t *dispp = lv_display_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_display_set_theme(dispp, theme);

    // Create single main screen
    mainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(mainScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(mainScreen, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(mainScreen, 0, 0);
    lv_obj_set_style_pad_all(mainScreen, 0, 0);

    // Create tabview with navbar
    globalNavbar.create(mainScreen);

    // Set tab change callback
    globalNavbar.setChangeCallback(onTabChanged);

    // Apply swipe setting
    globalNavbar.setSwipeEnabled(getswipeNavigation());

    // Create statusbar (floats above tabview)
    globalStatusbar.create(mainScreen);

    // Initialize screens with their tab content as parent
    scrHome.init(globalNavbar.getTabContent(TAB_HOME));
    scrPresets.init(globalNavbar.getTabContent(TAB_PRESETS));
    scrSettings.init(globalNavbar.getTabContent(TAB_SETTINGS));

    // Bring statusbar to front to ensure it's always visible
    if (globalStatusbar.container) {
        lv_obj_move_foreground(globalStatusbar.container);
    }

    // Load the main screen
    lv_screen_load(mainScreen);

    // Set initial state
    currentScreen = SCREEN_HOME;
    currentScr = &scrHome;

    screens[0] = &scrHome;
    screens[1] = &scrPresets;
    screens[2] = &scrSettings;

    // Delete the temporary screen that was used during splash/init
    if (tempScr != nullptr && tempScr != mainScreen) {
        lv_obj_del(tempScr);
    }
}

void ui_reinit(void)
{
    // Store current screen to restore after reinit
    SCREEN prevScreen = currentScreen;

    // Create OASMan splash screen
    set_brightness(0);// turn off brightness to not display gross artifacts while the logo is rendering
    delay(10); // not sure if this is needed, but just in case

    lv_obj_t *splashScr = applyRotationAndShowSplashScreen();

    // Reset state
    currentScreen = SCREEN_NONE;
    currentScr = nullptr;

    // Clean up each screen (virtual cleanup handles screen-specific objects)
    scrHome.cleanup();
    scrPresets.cleanup();
    scrSettings.cleanup();

    // Clean up statusbar
    globalStatusbar.cleanup();

    // Clean up navbar
    globalNavbar.cleanup();

    // Delete main screen
    if (mainScreen) {
        lv_obj_del(mainScreen);
        mainScreen = nullptr;
    }

    // Create new main screen
    mainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(mainScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(mainScreen, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(mainScreen, 0, 0);
    lv_obj_set_style_pad_all(mainScreen, 0, 0);

    // Recreate tabview with navbar
    globalNavbar.create(mainScreen);
    globalNavbar.setChangeCallback(onTabChanged);
    globalNavbar.setSwipeEnabled(getswipeNavigation());

    // Recreate statusbar
    globalStatusbar.create(mainScreen);

    // Reinitialize screens
    scrHome.init(globalNavbar.getTabContent(TAB_HOME));
    scrPresets.init(globalNavbar.getTabContent(TAB_PRESETS));
    scrSettings.init(globalNavbar.getTabContent(TAB_SETTINGS));

    // Bring statusbar to front
    if (globalStatusbar.container) {
        lv_obj_move_foreground(globalStatusbar.container);
    }

    // Update screens array
    screens[0] = &scrHome;
    screens[1] = &scrPresets;
    screens[2] = &scrSettings;

    // Load main screen
    lv_screen_load(mainScreen);

    // Restore to previous screen
    changeScreen(prevScreen, false);

    lv_obj_del(splashScr);
}

void changeScreen(SCREEN screen, bool animate)
{
    if (currentScreen == screen)
    {
        return;
    }

    uint32_t tabIndex;
    switch (screen)
    {
    case SCREEN_HOME:
        tabIndex = TAB_HOME;
        break;
    case SCREEN_PRESETS:
        tabIndex = TAB_PRESETS;
        break;
    case SCREEN_SETTINGS:
        tabIndex = TAB_SETTINGS;
        break;
    default:
        return;
    }

    // Set the active tab - this will trigger the callback
    globalNavbar.setActiveTab(tabIndex, animate);
}

void safetyModeMsgBoxCheck()
{
    bool safety_mode = (statusBittset & (1 << StatusPacketBittset::SAFETY_MODE)) != 0 ? 1 : 0;
    static bool hasShownSafetyMode = false;
    if (safety_mode && hasShownSafetyMode == false)
    {
        hasShownSafetyMode = true;
        // show safety mode dialog
        static char buf[40];
        snprintf(buf, sizeof(buf), "Save current height to preset %i?", currentPreset);
        currentScr->showMsgBox("Safe Boot is ENABLED!", "Safe boot is enabled meaning some features are disabled (your compressor & rise on start). Please check your settings are correct and then disable safe boot. This includes 'Pressure Sensor Rating PSI'. Then double check system functionality before disabling safety mode.", "View Settings", "Disable Anyway", []() -> void
                               {
                                    changeScreen(SCREEN_SETTINGS);
                                    showDialog("Please check your settings!", lv_color_hex(THEME_COLOR_LIGHT)); }, []() -> void
                               {
                                   Serial.println("Disabling safety mode");
                                   SafetyModePacket pkt(false);
                                   sendRestPacket(&pkt);
                                   showDialog("Safety mode disabled!", lv_color_hex(0xFF0000)); }, true);
    }
}

void screenLoop()
{
    // Update statusbar (battery, alerts)
    globalStatusbar.update();

    switch (currentScreen)
    {
    case SCREEN_HOME:
        scrHome.loop();
        break;
    case SCREEN_PRESETS:
        scrPresets.loop();
        break;
    case SCREEN_SETTINGS:
        scrSettings.loop();
        break;
    default:
        break;
    }

    resetTouchInputFrame();
}
