// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "utils/touch_lib.h"
#include "components/alert.h"

SCREEN currentScreen = SCREEN_NONE;

void ui_init(void)
{
    // Get reference to temporary screen from board_drivers_init (if any)
    lv_obj_t *tempScr = lv_screen_active();

    lv_display_t *dispp = lv_display_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_display_set_theme(dispp, theme);
    scrHome.init();
    scrPresets.init();
    scrSettings.init();
    changeScreen(SCREEN_HOME);

    // Delete the temporary screen that was used during splash/init
    if (tempScr != NULL && tempScr != scrHome.scr) {
        lv_obj_del(tempScr);
    }

    screens[0] = &scrHome;
    screens[1] = &scrPresets;
    screens[2] = &scrSettings;
}

void ui_reinit(void)
{
    // Store current screen to restore after reinit
    SCREEN prevScreen = currentScreen;

    // Create a temporary blank screen and switch to it first
    lv_obj_t *tempScr = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(tempScr, lv_color_hex(0x000000), 0);
    lv_screen_load(tempScr);

    // Force refresh to ensure screen switch completes
    lv_timer_handler();

    // Reset state
    currentScreen = SCREEN_NONE;
    currentScr = NULL;

    // Delete Alert objects first (C++ objects - LVGL objects are children of screen and will be deleted with it)
    if (scrHome.alert) {
        delete scrHome.alert;
        scrHome.alert = NULL;
    }
    if (scrPresets.alert) {
        delete scrPresets.alert;
        scrPresets.alert = NULL;
    }
    if (scrSettings.alert) {
        delete scrSettings.alert;
        scrSettings.alert = NULL;
    }

    // Delete old screens safely
    if (scrHome.scr) {
        lv_obj_del(scrHome.scr);
        scrHome.scr = NULL;
    }
    if (scrPresets.scr) {
        lv_obj_del(scrPresets.scr);
        scrPresets.scr = NULL;
    }
    if (scrSettings.scr) {
        lv_obj_del(scrSettings.scr);
        scrSettings.scr = NULL;
    }

    // Reinitialize screens
    scrHome.init();
    scrPresets.init();
    scrSettings.init();

    // Update screens array
    screens[0] = &scrHome;
    screens[1] = &scrPresets;
    screens[2] = &scrSettings;

    // Restore to previous screen
    changeScreen(prevScreen);

    // Delete temporary screen
    lv_obj_del(tempScr);
}

void changeScreen(SCREEN screen)
{
    if (currentScreen == screen)
    {
        return;
    }

    // lv_refr_now(lv_disp_get_default());

    currentScreen = screen;
    switch (screen)
    {
    case SCREEN_HOME:
        lv_screen_load(scrHome.scr);
        currentScr = &scrHome;
        break;
    case SCREEN_PRESETS:
        lv_screen_load(scrPresets.scr);
        currentScr = &scrPresets;
        break;
    case SCREEN_SETTINGS:
        lv_screen_load(scrSettings.scr);
        currentScr = &scrSettings;
        break;
    }

    // Sync alert icon state from global dismissed state when changing screens
    if (currentScr != NULL && currentScr->alert != NULL)
    {
        currentScr->alert->syncFromGlobal();
    }

    screenLoop(); // run one screen loop of the new screen to update things like the alert before it gets shown on screen
}

void safetyModeMsgBoxCheck()
{
    bool safety_mode = (statusBittset & (1 << StatusPacketBittset::SAFETY_MODE)) != 0 ? 1 : 0;
    static bool hasShownSafetyMode = false;
    if (safety_mode && hasShownSafetyMode == false)
    {
        hasShownSafetyMode = true;
        // show safety mode dialog
        static char buf[40];
        snprintf(buf, sizeof(buf), "Save current height to preset %i?", currentPreset);
        currentScr->showMsgBox("Safe Boot is ENABLED!", "Safe boot is enabled meaning some features are disabled (your compressor & rise on start). Please check your settings are correct and then disable safe boot. This includes 'Pressure Sensor Rating PSI'. Then double check system functionality before disabling safety mode.", "View Settings", "Disable Anyway", []() -> void
                               { 
                                    changeScreen(SCREEN_SETTINGS); 
                                    showDialog("Please check your settings!", lv_color_hex(THEME_COLOR_LIGHT)); }, []() -> void
                               {
                                   Serial.println("Disabling safety mode");
                                   SafetyModePacket pkt(false);
                                   sendRestPacket(&pkt);
                                   showDialog("Safety mode disabled!", lv_color_hex(0xFF0000)); }, true);
    }
}

void screenLoop()
{
    switch (currentScreen)
    {
    case SCREEN_HOME:
        scrHome.loop();
        break;
    case SCREEN_PRESETS:
        scrPresets.loop();
        break;
    case SCREEN_SETTINGS:
        scrSettings.loop();
        break;
    }

    resetTouchInputFrame();
}
