// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "utils/touch_lib.h"

SCREEN currentScreen = SCREEN_NONE;

void ui_init(void)
{
    lv_disp_t *dispp = lv_display_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    scrHome.init();
    scrPresets.init();
    scrSettings.init();
    scrMain.ui____initial_actions0 = lv_obj_create(NULL);
    changeScreen(SCREEN_HOME);

    screens[0] = &scrHome;
    screens[1] = &scrPresets;
    screens[2] = &scrSettings;
}

void changeScreen(SCREEN screen)
{
    if (currentScreen == screen)
    {
        return;
    }

    // lv_refr_now(lv_disp_get_default());

    currentScreen = screen;
    switch (screen)
    {
    case SCREEN_MAIN:
        lv_disp_load_scr(scrMain.ui_scrMain);
        break;
    case SCREEN_HOME:
        lv_disp_load_scr(scrHome.scr);
        currentScr = &scrHome;
        break;
    case SCREEN_PRESETS:
        lv_disp_load_scr(scrPresets.scr);
        currentScr = &scrPresets;
        break;
    case SCREEN_SETTINGS:
        lv_disp_load_scr(scrSettings.scr);
        currentScr = &scrSettings;
        break;
    }

    screenLoop(); // run one screen loop of the new screen to update things like the alert before it gets shown on screen
}

void safetyModeMsgBoxCheck()
{
    bool safety_mode = (statusBittset & (1 << StatusPacketBittset::SAFETY_MODE)) != 0 ? 1 : 0;
    static bool hasShownSafetyMode = false;
    if (safety_mode && hasShownSafetyMode == false)
    {
        hasShownSafetyMode = true;
        // show safety mode dialog
        static char buf[40];
        snprintf(buf, sizeof(buf), "Save current height to preset %i?", currentPreset);
        currentScr->showMsgBox("Safe Boot is ENABLED!", "Safe boot is enabled meaning some features are disabled (your compressor & rise on start). Please check your settings are correct and then disable safe boot. This includes 'Pressure Sensor Rating PSI' and 'Calibrate Pressure Sensors' to check and reassign them if they are not plugged into the correct ports.", "View Settings", "Disable Anyway", []() -> void
                               { 
                                    changeScreen(SCREEN_SETTINGS); 
                                    showDialog("Please check your settings!", lv_color_hex(THEME_COLOR_LIGHT)); }, []() -> void
                               {
                                   Serial.println("Disabling safety mode");
                                   SafetyModePacket pkt(false);
                                   sendRestPacket(&pkt);
                                   showDialog("Safety mode disabled!", lv_color_hex(0xFF0000)); }, true);
    }
}

void screenLoop()
{
    switch (currentScreen)
    {
    case SCREEN_MAIN:
        ui_scrMain_loop();
        break;
    case SCREEN_HOME:
        scrHome.loop();
        break;
    case SCREEN_PRESETS:
        scrPresets.loop();
        break;
    case SCREEN_SETTINGS:
        scrSettings.loop();
        break;
    }

    resetTouchInputFrame();
}
