// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#include "Arduino.h"
#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "screens/ui_scrMain.h"
#include "screens/ui_scrHome.h"
#include "screens/ui_scrPresets.h"
#include "screens/ui_scrSettings.h"

typedef enum
{
    SCREEN_MAIN,
    SCREEN_HOME,
    SCREEN_PRESETS,
    SCREEN_SETTINGS
} SCREEN;

void ui_init(void);
void changeScreen(SCREEN screen);
void screenLoop();

extern SCREEN currentScreen;

#endif
