// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#include "Arduino.h"
#include "lvgl.h"

/* Must be before SCREEN_MODE_CIRCLE branching — device_lib_exports.h defines the macro per board. */
#include "device_lib_exports.h"

#ifdef SCREEN_MODE_CIRCLE
#include "ui_circle/screens/circle_scrHome.h"
#else
#include "screens/ui_scrHome.h"
#include "screens/ui_scrPresets.h"
#endif
#include "screens/ui_scrSettings.h"

#include "utils/util.h"

typedef enum
{
    SCREEN_NONE,
    SCREEN_HOME,
    SCREEN_PRESETS,
    SCREEN_SETTINGS
} SCREEN;

void ui_init(void);
void ui_reinit(void);
void changeScreen(SCREEN screen, bool animate = true);
void screenLoop();
void safetyModeMsgBoxCheck();

extern SCREEN currentScreen;

#endif
